name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Deploy app
        run: |
          # Replace <deploy_folder> with the actual folder where you want to deploy the app
          mkdir -p deploy_folder
          cp -r dist/* deploy_folder
